export const products = [
  {
    id: 1,
    title: "Samsung GalaxyA12",
    url: "https://static-www.o2.co.uk/sites/default/files/black-samsung-galaxy-a12-sku-header-221220.png",
    originalPrice: 179.00,
    salePrice: 149.00,
    rating: 4.5,
    description: "The biggest Pro camera system upgrade ever. 6.1-inch Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip. Superfast 5G.1 Durable design and a huge leap in battery life.",
  },
  {
    id: 2,
    title: "Samsung Galaxy Tab A8",
    url: "https://static-www.o2.co.uk/sites/default/files/samsung-galaxy-tab-a8-sku-header-141221.png",
    originalPrice: 300.00,
    salePrice: null,
    rating: 5,
    description:"The Galaxy Tab A8 4G is built to impress, with beautifully balanced 3D audio and an immersive 10.5-inch display. And with Samsung Kids and Samsung TV Plus, it’s a great fit for the entire family." ,
  },
  {
    id: 3,
    title: "Iphone 13 Pro Max",
    url: "https://static-www.o2.co.uk/sites/default/files/iphone-13-pro-max-sierra-sku-header-141021_0.png",
    originalPrice: 999.00,
    salePrice: null,
    rating: 5,
    description:"Apple iPhone 13 Pro Max. 5G to download movies and stream high-quality video. Bright 6.7-inch Super Retina XDR display. Powerful A15 Bionic chip and ProMotion for the first time ever on an iPhone. The largest camera sensor ever and better in lowlight situations with faster shutter speeds and beautiful portrait photos" ,
  },
  {
    id: 4,
    title: "Iphone 13 Pro",
    url: "https://static-www.o2.co.uk/sites/default/files/iphone-13-pro-graphite-sku-header-141021_1.png",
    originalPrice: 945.00,
    salePrice: 910.00,
    rating: 4.5,
    description: "The biggest Pro camera system upgrade ever. 6.1-inch Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip. Superfast 5G.1 Durable design and a huge leap in battery life.",
  },
  {
    id: 5,
    title: "Iphone 13",
    url: "https://static-www.o2.co.uk/sites/default/files/iphone-13-blue-sku-header-141021.png",
    originalPrice: 849.00,
    salePrice: null,
    rating: 5,
    description: "Apple iPhone 13. 5G to download movies and stream high-quality video. Bright 6.1-inch Super Retina XDR display. Powerful A15 Bionic chip. The fastest CPU in an iPhone ever at 50% faster than any other smartphone." ,
  },
  {
    id: 6,
    title: "Ipad Pro 2021",
    url: "https://static-www.o2.co.uk/sites/default/files/apple-ipad-pro-11-space-grey-sku-header-200421.png",
    originalPrice: 925.00,
    salePrice: 898.00,
    rating: 5,
    description: "Powerful Apple M1 chip. An 11 inch Liquid Retina display. With pro cameras and a LiDAR Scanner for stunning photos, videos, and immersive AR. The iPad Pro is not only gorgeous, but super portable. And, 5G gives you blazing speeds away from Wi-Fi" ,
  },
  {
    id: 7,
    title: "Apple Iphone 11",
    url: "https://static-www.o2.co.uk/sites/default/files/apple-iphone-11-black-sku-header.png",
    originalPrice: 599.00,
    salePrice: 550.00,
    rating: 4,
    description: "Shoot 4K videos, take beautiful portraits and sweeping landscapes in incredible detail with the dual-camera system on iPhone 11’s 6.1-inch Liquid Retina display" ,
  },
  {
    id: 8,
    title: "OPPO A16s",
    url: "https://static-www.o2.co.uk/sites/default/files/oppo-a16s-black-sku-header-261021.png",
    originalPrice: 130.00,
    salePrice: 100.00,
    rating: 4.5,
    description: "Bigger battery. Better photos. The OPPO A16s comes with a big screen, a huge 5000mAh battery and a designed-to-shine triple camera all in one." ,
  },
  {
    id: 9,
    title: "Google Pixel 6",
    url: "https://static-www.o2.co.uk/sites/default/files/google-pixel-6-black-sku-header-131021.png",
    originalPrice: 140.00,
    salePrice: 105.00,
    rating: 4.5,
    description: "Want a phone that adapts to you? Meet Pixel 6. Powered by the custom-built Google Tensor processor, it’s fast, smart, and secure." ,
  },
  {
    id: 10,
    title: "Samsung Galaxy S21",
    url: "https://static-www.o2.co.uk/sites/default/files/samsung-r9-black-sku-header-141221.png",
    originalPrice: 769.00,
    salePrice: null,
    rating: 5,
    description: "Get ready to do even more, the Galaxy S21 FE is built for the bold. Supercharge your socials with selfies and stories using a 32MP front-facing camera. Enjoy scrolling all day long with a powerful processor. And with a massive AI-powered battery, it’ll get you through work and play." ,
  },
  {
    id: 11,
    title: "Apple Watch Series 7",
    url: "https://static-www.o2.co.uk/sites/default/files/apple-watch-s7-nike-midnight-41mm-sku-header--051021.png",
    originalPrice: 369.00,
    salePrice: 335.00,
    rating: 5,
    description: "With Apple Watch Nike Series 7 and the built-in Nike Run Club app, you can track your workouts and listen to Guided Runs. And turn on Nike Twilight Mode for enhanced visibility.",
  },
  {
    id: 12,
    title: "Apple Watch Series 6",
    url: "https://static-www.o2.co.uk/sites/default/files/apple-s6-watch-44-red-sku-header.png",
    originalPrice: 320.00,
    salePrice: 289.00,
    rating: 4.5,
    description: "Measure your blood oxygen level. Take an ECG anytime, anywhere. And easily see your fitness metrics on the enhanced Always-On Retina display. The future of health is on your wrist." ,
  },
  {
    id: 13,
    title: "Apple Airpods Pro",
    url: "https://static-www.o2.co.uk/sites/default/files/airpods-3rd-gen-sku-header-191021_0.png",
    originalPrice: 189.00,
    salePrice: 150.00,
    rating: 4.5,
    description: "Introducing the all-new AirPods. Featuring spatial audio that places sound all around you, Adaptive EQ that tunes music to your ears, and longer battery life. It’s all sweat and water resistant and delivers an experience that’s simply magical. A perfect pair with the new iPhone 13.",
    
  },
];
